name: Create branch
on: workflow_dispatch
jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Create branch
        env:
          GH_TOKEN: ${{ secrets.GH_ACTION_2 }}
        run: |
          gh codespace create -b "branch-from-action"

