name: Create branch
on: workflow_dispatch
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Create branch
        run: |
          echo "Creating commit..."
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git commit -m "commit from action" --allow-empty
          git push
