name: Create branch
on: workflow_dispatch
env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Create branch
        run: |
          echo "Creating branch..."
          gh codespace create -b action-branch
