name: Create branch
on: workflow_dispatch
env:
  GH_TOKEN: ${{ secrets.GH_ACTION_2 }}
jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Create branch
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git switch -c "action-branch"
          git commit -m "action commit" --allow-empty
          gh pr create

