name: Create branch
on: workflow_dispatch
env:
  GH_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Create branch
        run: |
          git switch -c "action-branch"
          git commit -m "action commit" --allow-empty
          gh pr create

