name: Create branch
on: workflow_dispatch
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: 'main'
          path: 'main'
      - name: Create branch
        run: gh codespace create -b action-branch
